version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    container_name: adm
    environment:
      POSTGRES_USER: corinthians
      POSTGRES_PASSWORD: sccp1910
      POSTGRES_DB: adm
    volumes:
      - adm_pg_data:/bitnami/postgresql

  app:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://corinthians:sccp1910@postgres:5432/adm
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  adm_pg_data:
