version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    container_name: adm
    environment:
      POSTGRES_USER: corinthians
      POSTGRES_PASSWORD: sccp1910
      POSTGRES_DB: adm
    volumes:
      - adm_pg_data:/bitnami/postgresql

volumes:
  adm_pg_data:
